-- The existing Supabase project uses auth-compatible UUID profile IDs.
-- This migration creates the tracker tables with UUID user references.
create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  name text not null,
  description text default '',
  status text not null default 'not-started',
  progress int not null default 0,
  exam_date date,
  created_at timestamptz not null default now()
);
create table if not exists public.syllabus_topics (
  id bigint generated by default as identity primary key,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  parent_id bigint references public.syllabus_topics(id) on delete cascade,
  name text not null,
  status text not null default 'not-started',
  progress int not null default 0,
  created_at timestamptz not null default now()
);
create table if not exists public.study_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  subject_id bigint references public.subjects(id) on delete set null,
  minutes int not null,
  note text default '',
  timer_session_id bigint,
  logged_at timestamptz not null default now()
);
create table if not exists public.timer_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  subject_id bigint references public.subjects(id) on delete set null,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  seconds int default 0,
  heartbeat_at timestamptz
);
create table if not exists public.groups (
  id bigint generated by default as identity primary key,
  name text not null,
  description text default '',
  owner_id uuid not null references public.users(id) on delete cascade,
  invite_code text unique,
  created_at timestamptz not null default now()
);
create table if not exists public.group_members (
  group_id bigint references public.groups(id) on delete cascade,
  user_id uuid references public.users(id) on delete cascade,
  role text not null default 'member',
  joined_at timestamptz not null default now(),
  primary key (group_id, user_id)
);
create table if not exists public.files (
  id bigint generated by default as identity primary key,
  group_id bigint references public.groups(id) on delete cascade,
  user_id uuid references public.users(id) on delete cascade,
  subject_id bigint references public.subjects(id) on delete cascade,
  topic_id bigint references public.syllabus_topics(id) on delete set null,
  original_name text not null,
  stored_name text not null,
  storage_path text not null,
  storage_bucket text not null,
  mime text,
  size bigint,
  folder text default 'General',
  display_name text,
  caption_stored_name text,
  created_at timestamptz not null default now()
);
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  group_id bigint references public.groups(id) on delete cascade,
  user_id uuid references public.users(id) on delete cascade,
  body text not null,
  file_id bigint references public.files(id) on delete set null,
  created_at timestamptz not null default now()
);
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade,
  title text not null,
  due_date date,
  done boolean default false,
  created_at timestamptz not null default now()
);
create table if not exists public.goals (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade,
  title text not null,
  target text default '',
  done boolean default false,
  created_at timestamptz not null default now()
);
create table if not exists public.warrants (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade,
  reason text not null,
  status text default 'open',
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;
alter table public.subjects enable row level security;
alter table public.syllabus_topics enable row level security;
alter table public.study_logs enable row level security;
alter table public.timer_sessions enable row level security;
alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.files enable row level security;
alter table public.messages enable row level security;
alter table public.tasks enable row level security;
alter table public.goals enable row level security;
alter table public.warrants enable row level security;

create policy "tracker users can manage own subjects" on public.subjects for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "tracker users can manage own topics" on public.syllabus_topics for all using (subject_id in (select id from public.subjects where user_id = auth.uid())) with check (subject_id in (select id from public.subjects where user_id = auth.uid()));
create policy "tracker users can manage own logs" on public.study_logs for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "tracker users can manage own timers" on public.timer_sessions for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "tracker users can manage own tasks" on public.tasks for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "tracker users can manage own goals" on public.goals for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "tracker users can manage own warrants" on public.warrants for all using (user_id = auth.uid()) with check (user_id = auth.uid());
