-- ============================================================
-- Group tasks migration — run in Supabase SQL Editor
-- ============================================================

-- Table for admin-assigned tasks within a study group
create table if not exists group_tasks (
  id bigint generated by default as identity primary key,
  group_id bigint not null references groups(id) on delete cascade,
  assigned_to uuid references users(id) on delete set null,
  created_by uuid not null references users(id) on delete cascade,
  title text not null,
  description text default '',
  due_date date,
  done boolean not null default false,
  created_at timestamptz not null default now()
);

-- RLS: all group members can read tasks
alter table group_tasks enable row level security;

create policy "group members can read group tasks" on group_tasks
  for select using (
    group_id in (select group_id from group_members where user_id = auth.uid())
  );

-- Admins can do everything (insert, update, delete)
create policy "group admins can insert tasks" on group_tasks
  for insert with check (
    group_id in (select group_id from group_members where user_id = auth.uid() and role = 'admin')
  );

create policy "group admins can update tasks" on group_tasks
  for update using (
    group_id in (select group_id from group_members where user_id = auth.uid() and role = 'admin')
  );

create policy "group admins can delete tasks" on group_tasks
  for delete using (
    group_id in (select group_id from group_members where user_id = auth.uid() and role = 'admin')
  );

-- Also enable realtime for group_tasks and messages so task assignments
-- and new chat messages propagate live to all members.
do $$ begin
  alter publication supabase_realtime add table group_tasks;
exception when duplicate_object then
  raise notice 'group_tasks already in realtime — skipping';
end $$;

do $$ begin
  alter publication supabase_realtime add table messages;
exception when duplicate_object then
  raise notice 'messages already in realtime — skipping';
end $$;
