-- Run in Supabase SQL editor. The server uses these Postgres tables via service role.
create table if not exists users (id uuid primary key, name text not null, email text unique not null, role text not null default 'student', created_at timestamptz not null default now());
create table if not exists subjects (id bigint generated by default as identity primary key, user_id uuid not null references users(id) on delete cascade, name text not null, description text default '', status text not null default 'not-started', progress int not null default 0, exam_date date, created_at timestamptz not null default now());
create table if not exists syllabus_topics (id bigint generated by default as identity primary key, subject_id bigint not null references subjects(id) on delete cascade, parent_id bigint references syllabus_topics(id) on delete cascade, name text not null, status text not null default 'not-started', progress int not null default 0, created_at timestamptz not null default now());
create table if not exists study_logs (id bigint generated by default as identity primary key, user_id uuid not null references users(id) on delete cascade, subject_id bigint references subjects(id) on delete set null, minutes int not null, note text default '', timer_session_id bigint, logged_at timestamptz not null default now());
create table if not exists timer_sessions (id bigint generated by default as identity primary key, user_id uuid not null references users(id) on delete cascade, subject_id bigint references subjects(id) on delete set null, started_at timestamptz not null default now(), ended_at timestamptz, seconds int default 0, heartbeat_at timestamptz);
create table if not exists groups (id bigint generated by default as identity primary key, name text not null, description text default '', owner_id uuid not null references users(id) on delete cascade, invite_code text unique, created_at timestamptz not null default now());
create table if not exists group_members (group_id bigint references groups(id) on delete cascade, user_id uuid references users(id) on delete cascade, role text not null default 'member', joined_at timestamptz not null default now(), primary key(group_id,user_id));
create table if not exists files (id bigint generated by default as identity primary key, group_id bigint references groups(id) on delete cascade, user_id uuid references users(id) on delete cascade, subject_id bigint references subjects(id) on delete cascade, topic_id bigint references syllabus_topics(id) on delete set null, original_name text not null, stored_name text not null, storage_path text not null, storage_bucket text not null, mime text, size bigint, folder text default 'General', display_name text, caption_stored_name text, created_at timestamptz not null default now());
create table if not exists messages (id bigint generated by default as identity primary key, group_id bigint references groups(id) on delete cascade, user_id uuid references users(id) on delete cascade, body text not null, file_id bigint references files(id) on delete set null, created_at timestamptz not null default now());
create table if not exists tasks (id bigint generated by default as identity primary key, user_id uuid references users(id) on delete cascade, title text not null, due_date date, done boolean default false, created_at timestamptz not null default now());
create table if not exists goals (id bigint generated by default as identity primary key, user_id uuid references users(id) on delete cascade, title text not null, target text default '', done boolean default false, created_at timestamptz not null default now());
create table if not exists warrants (id bigint generated by default as identity primary key, user_id uuid references users(id) on delete cascade, reason text not null, status text default 'open', created_at timestamptz not null default now());

-- Upgrade an older project where the local profile table already existed.
-- The Express server uses the service role for trusted API operations. These
-- policies protect the tables if the public Supabase client is used directly.
alter table users enable row level security;
alter table subjects enable row level security;
alter table syllabus_topics enable row level security;
alter table study_logs enable row level security;
alter table timer_sessions enable row level security;
alter table groups enable row level security;
alter table group_members enable row level security;
-- File metadata is written only through authenticated Express routes, which
-- enforce ownership/group membership before inserting or reading records.
alter table files disable row level security;
alter table messages enable row level security;
alter table tasks enable row level security;
alter table goals enable row level security;
alter table warrants enable row level security;

drop policy if exists "users can read own profile" on users;
drop policy if exists "users can manage own subjects" on subjects;
drop policy if exists "users can manage own topics" on syllabus_topics;
drop policy if exists "users can manage own study logs" on study_logs;
drop policy if exists "users can manage own timers" on timer_sessions;
drop policy if exists "members can read groups" on groups;
drop policy if exists "members can read membership" on group_members;
drop policy if exists "members can read group files" on files;
drop policy if exists "users can create personal file records" on files;
drop policy if exists "members can create group file records" on files;
drop policy if exists "authenticated file metadata insert" on files;
drop policy if exists "public file metadata insert" on files;
drop policy if exists "members can read group messages" on messages;
drop policy if exists "users can manage own tasks" on tasks;
drop policy if exists "users can manage own goals" on goals;
drop policy if exists "users can manage own warrants" on warrants;
drop policy if exists "authenticated users can upload personal files" on storage.objects;
drop policy if exists "authenticated users can read personal files" on storage.objects;
drop policy if exists "authenticated users can upload group files" on storage.objects;
drop policy if exists "authenticated users can read group files" on storage.objects;

create policy "users can read own profile" on users for select using (id = auth.uid());
create policy "users can manage own subjects" on subjects for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "users can manage own topics" on syllabus_topics for all using (subject_id in (select id from subjects where user_id = auth.uid())) with check (subject_id in (select id from subjects where user_id = auth.uid()));
create policy "users can manage own study logs" on study_logs for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "users can manage own timers" on timer_sessions for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "members can read groups" on groups for select using (id in (select group_id from group_members where user_id = auth.uid()));
create policy "members can read membership" on group_members for select using (user_id = auth.uid() or group_id in (select group_id from group_members gm where gm.user_id = auth.uid()));
create policy "members can read group files" on files for select using (user_id = auth.uid() or group_id in (select group_id from group_members where user_id = auth.uid()));
create policy "members can read group messages" on messages for select using (group_id in (select group_id from group_members where user_id = auth.uid()));
create policy "users can manage own tasks" on tasks for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "users can manage own goals" on goals for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "users can manage own warrants" on warrants for all using (user_id = auth.uid()) with check (user_id = auth.uid());

insert into storage.buckets (id, name, public)
values ('personal-files', 'personal-files', true), ('group-files', 'group-files', true)
on conflict (id) do nothing;

create policy "authenticated users can upload personal files" on storage.objects for insert to authenticated with check (bucket_id = 'personal-files' and (storage.foldername(name))[1] = 'users' and (storage.foldername(name))[2] = auth.uid()::text);
create policy "authenticated users can read personal files" on storage.objects for select to authenticated using (bucket_id = 'personal-files' and (storage.foldername(name))[1] = 'users' and (storage.foldername(name))[2] = auth.uid()::text);
create policy "authenticated users can upload group files" on storage.objects for insert to authenticated with check (bucket_id = 'group-files' and exists (select 1 from group_members where group_id::text = (storage.foldername(name))[2] and user_id = auth.uid()));
create policy "authenticated users can read group files" on storage.objects for select to authenticated using (bucket_id = 'group-files' and exists (select 1 from group_members where group_id::text = (storage.foldername(name))[2] and user_id = auth.uid()));
